
PREFIX re:   <http://base.relat.io#>


# Construct graph out of selected triples
CONSTRUCT {{ 
    ?o       ?p_o_o         ?o_o       .
    ?entity  ?p_o           ?o         .
    ?s       ?p_s           ?entity    .
    ?s_s     ?p_s_s         ?s         .
    
    ?o_o     rdfs:label ?o_o_label .
    ?o       rdfs:label ?o_label   .
    ?entity  rdfs:label "{label}"  .
    ?s       rdfs:label ?s_label   .
    ?s_s     rdfs:label ?s_s_label .
}}


# Select triples containing center node
WHERE {{ 

    {{
        # Select center node
        ?entity a          re:Entity ;
                rdfs:label "{label}" .
        
        # Get all triples with center node as the subject
        ?entity ?p_o   ?o   . 
        ?o      ?p_o_o ?o_o .
        
        # Retrieve prefLabels (if any)
        ?o   rdfs:label ?o_label   .
        ?o_o rdfs:label ?o_o_label .
        OPTIONAL {{ ?p_o   rdfs:label ?p_o_label   }}
        OPTIONAL {{ ?p_o_o rdfs:label ?p_o_o_label }}
        
    }} UNION {{
    
        # Select center node
        ?entity a          re:Entity ;
                rdfs:label "{label}" .
        
        # Get all triples with center node as the object
        ?s   ?p_s   ?entity . 
        ?s_s ?p_s_s ?s      .
        
        # Retrieve prefLabels (if any)
        ?s   rdfs:label ?s_label   .
        ?s_s rdfs:label ?s_s_label .
        OPTIONAL {{ ?p_s   rdfs:label ?p_s_label   }}
        OPTIONAL {{ ?p_s_s rdfs:label ?p_s_s_label }}
        
    }}

}}
